import os

slicerSettings = []

Percent = float


def setSlicerSettings(shape,
                      cut: float = None,
                      cut_x: float = None,
                      cut_y: float = None,
                      adaptive_slicing: float = None,
                      adaptive_slicing_quality: Percent = None,
                      avoid_crossing_perimeters: float = None,
                      bed_shape: str = None,
                      bed_temperature: float = None,
                      before_layer_gcode: str = None,
                      between_objects_gcode: str = None,
                      bottom_infill_pattern: str = None,
                      bottom_solid_layers: float = None,
                      bridge_acceleration: float = None,
                      bridge_fan_speed: float = None,
                      bridge_flow_ratio: float = None,
                      bridge_speed: float = None,
                      brim_connections_width: float = None,
                      brim_width: float = None,
                      compatible_printers: str = None,
                      complete_objects: float = None,
                      cooling: float = None,
                      default_acceleration: float = None,
                      duplicate: float = None,
                      disable_fan_first_layers: float = None,
                      dont_support_bridges: float = None,
                      duplicate_distance: float = None,
                      end_filament_gcode: str = None,
                      end_gcode: str = None,
                      external_perimeter_extrusion_width: float = None,
                      external_perimeter_speed: Percent = None,
                      external_perimeters_first: float = None,
                      extra_perimeters: float = None,
                      extruder_clearance_height: float = None,
                      extruder_clearance_radius: float = None,
                      extruder_offset: float = None,
                      extrusion_axis: float = None,
                      extrusion_multiplier: float = None,
                      extrusion_width: float = None,
                      fan_always_on: bool = None,
                      fan_below_layer_time: float = None,
                      filament_colour: str = None,
                      filament_cost: float = None,
                      filament_density: float = None,
                      filament_diameter: str = None,
                      filament_max_volumetric_speed: float = None,
                      filament_notes: str = None,
                      filament_settings_id: float = None,
                      fill_angle: float = None,
                      fill_density: Percent = None,
                      fill_gaps: float = None,
                      fill_pattern: str = None,
                      first_layer_acceleration: float = None,
                      first_layer_bed_temperature: float = None,
                      first_layer_extrusion_width: float = None,
                      first_layer_height: float = None,
                      first_layer_speed: float = None,
                      first_layer_temperature: float = None,
                      gap_fill_speed: float = None,
                      gcode_arcs: float = None,
                      gcode_comments: float = None,
                      gcode_flavor: str = None,
                      has_heatbed: float = None,
                      host_type: str = None,
                      infill_acceleration: float = None,
                      infill_every_layers: float = None,
                      infill_extruder: float = None,
                      infill_extrusion_width: float = None,
                      infill_first: float = None,
                      infill_only_where_needed: float = None,
                      infill_overlap: Percent = None,
                      infill_speed: float = None,
                      interface_shells: float = None,
                      interior_brim_width: float = None,
                      layer_gcode: str = None,
                      layer_height: float = None,
                      match_horizontal_surfaces: float = None,
                      max_fan_speed: float = None,
                      max_layer_height: float = None,
                      max_print_speed: float = None,
                      max_volumetric_speed: float = None,
                      min_fan_speed: float = None,
                      min_layer_height: float = None,
                      min_print_speed: float = None,
                      min_skirt_length: float = None,
                      notes: str = None,
                      nozzle_diameter: float = None,
                      octoprint_apikey: str = None,
                      only_retract_when_crossing_perimeters: float = None,
                      ooze_prevention: float = None,
                      output_filename_format: str = None,
                      overhangs: float = None,
                      perimeter_acceleration: float = None,
                      perimeter_extruder: float = None,
                      perimeter_extrusion_width: float = None,
                      perimeter_speed: float = None,
                      perimeters: float = None,
                      post_process: str = None,
                      pressure_advance: float = None,
                      print_host: str = None,
                      print_settings_id: str = None,
                      printer_notes: str = None,
                      printer_settings_id: str = None,
                      raft_layers: float = None,
                      regions_overlap: float = None,
                      resolution: float = None,
                      retract_before_travel: float = None,
                      retract_layer_change: float = None,
                      retract_length: float = None,
                      retract_length_toolchange: float = None,
                      retract_lift: float = None,
                      retract_lift_above: float = None,
                      retract_lift_below: float = None,
                      retract_restart_extra: float = None,
                      retract_restart_extra_toolchange: float = None,
                      retract_speed: float = None,
                      seam_position: str = None,
                      sequential_print_priority: float = None,
                      serial_port: str = None,
                      serial_speed: float = None,
                      skirt_distance: float = None,
                      skirt_height: float = None,
                      skirts: float = None,
                      slowdown_below_layer_time: float = None,
                      small_perimeter_speed: float = None,
                      solid_infill_below_area: float = None,
                      solid_infill_every_layers: float = None,
                      solid_infill_extruder: float = None,
                      solid_infill_extrusion_width: float = None,
                      solid_infill_speed: float = None,
                      spiral_vase: float = None,
                      standby_temperature_delta: float = None,
                      start_filament_gcode: str = None,
                      start_gcode: str = None,
                      support_material: bool = None,
                      support_material_angle: float = None,
                      support_material_buildplate_only: float = None,
                      support_material_contact_distance: float = None,
                      support_material_enforce_layers: float = None,
                      support_material_extruder: float = None,
                      support_material_extrusion_width: float = None,
                      support_material_interface_extruder: float = None,
                      support_material_interface_extrusion_width: float = None,
                      support_material_interface_layers: float = None,
                      support_material_interface_spacing: float = None,
                      support_material_interface_speed: Percent = None,
                      support_material_max_layers: float = None,
                      support_material_pattern: str = None,
                      support_material_spacing: float = None,
                      support_material_speed: float = None,
                      support_material_threshold: Percent = None,
                      temperature: float = None,
                      thin_walls: float = None,
                      threads: float = None,
                      toolchange_gcode: str = None,
                      top_infill_extrusion_width: float = None,
                      top_infill_pattern: str = None,
                      top_solid_infill_speed: float = None,
                      top_solid_layers: float = None,
                      travel_speed: float = None,
                      use_firmware_retraction: float = None,
                      use_relative_e_distances: float = None,
                      use_set_and_wait_bed: float = None,
                      use_set_and_wait_extruder: float = None,
                      use_volumetric_e: float = None,
                      vibration_limit: float = None,
                      wipe: float = None,
                      xy_size_compensation: float = None,
                      z_offset: float = None,
                      z_steps_per_mm: float = None
                      ) -> str:
    args = locals()
    del args["shape"]
    s = []
    for k, v in args.items():
        if isinstance(v, bool):
            s.append(f'--{k.replace("_","-")}')
        elif v is not None:
            s.append(f'--{k.replace("_","-")}={v}')

    setting = " ".join(s)
    # slicerSettings.append(setting)
    shape.slicerSettings = setting


ini = os.path.join(os.path.dirname(__file__), 'cube_normal_duramic_black.ini')


def getSliceCmd(shape, stl: str):
    cmd = [
        r'%userprofile%\Slic3r-1.3.0.64bit\Slic3r-console.exe',
        '--load',
        ini
    ]
    if "slicerSettings" in dir(shape):
        cmd.append(shape.slicerSettings)
    cmd.append(stl)
    return " ".join(cmd)
